name: Lint Commit Messages

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: rm tsconfig.json

      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: "./.commitlintrc.json"
